In [1]:
# !pip install seaborn
# !pip install yellowbrick
# !pip install geopandas
# !pip install openpyxl

In [2]:
import pandas as pd
import geopandas as gpd

In [3]:
df = pd.read_csv('C:/Users/hyeon/OneDrive/Desktop/2026-1/공모전/데이터분석/데이터/반지하/서울시_주택인허가_동별개요.csv', encoding = 'cp949')
df.head()

C:\Users\hyeon\AppData\Local\Temp\ipykernel_30448\3457126806.py:1: DtypeWarning: Columns (11,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/hyeon/OneDrive/Desktop/2026-1/공모전/데이터분석/데이터/반지하/서울시_주택인허가_동별개요.csv', encoding = 'cp949')

,대지위치,시군구코드명,법정동코드명,대지구분코드명,주지번,부지번,동별개요일련번호,주택대장일련번호,건물명,특수지명,...,지상층수,높이,승용승강기인용수정보,비상용승강기인용수정보,층시작높이값,반자높이값,계단유효너비,복도너비,외벽두께,인접세대벽두께
0,서울특별시 성북구 하월곡동,서울특별시 성북구,하월곡동,NaN,0.0,0.0,1007404,100726,샹그레빌 아파트,NaN,...,1.0,3.45,0.0,0.0,0.0,2.5,0.0,0.0,25.0,0.0
1,서울특별시 성북구 하월곡동,서울특별시 성북구,하월곡동,NaN,0.0,0.0,1007403,100726,샹그레빌 아파트,NaN,...,1.0,2.40,0.0,0.0,2.4,2.14,0.0,0.0,25.0,0.0
2,서울특별시 성북구 하월곡동,서울특별시 성북구,하월곡동,NaN,0.0,0.0,1007402,100726,샹그레빌 아파트,NaN,...,1.0,2.40,0.0,0.0,2.4,2.14,0.0,0.0,25.0,0.0
3,서울특별시 성북구 하월곡동,서울특별시 성북구,하월곡동,NaN,0.0,0.0,1007401,100726,샹그레빌 아파트,NaN,...,0.0,11.30,0.0,0.0,0.0,2.9,0.0,0.0,30.0,0.0
4,서울특별시 성북구 하월곡동,서울특별시 성북구,하월곡동,NaN,0.0,0.0,1007400,100726,샹그레빌 아파트,NaN,...,0.0,6.00,0.0,0.0,0.0,5.2,0.0,0.0,0.0,0.0

In [4]:
print(df.shape)
print(df.columns)

(58372, 42)
Index(['대지위치', '시군구코드명', '법정동코드명', '대지구분코드명', '주지번', '부지번', '동별개요일련번호',
       '주택대장일련번호', '건물명', '특수지명', '블록번호', '로트번호', '주부속구분코드명', '동명', '주용도코드명',
       '국민임대세대수', '공공임대5년세대수', '공공임대10년세대수', '공공임대기타세대수', '공공임대총세대수',
       '공공분양세대수', '사원임대세대수', '근로복지세대수', '민간임대세대수', '민간분양세대수', '구조코드명', '지붕코드명',
       '건축면적', '연면적', '지하면적', '용적률산정연면적', '지하층수', '지상층수', '높이', '승용승강기인용수정보',
       '비상용승강기인용수정보', '층시작높이값', '반자높이값', '계단유효너비', '복도너비', '외벽두께', '인접세대벽두께'],
      dtype='object')

In [5]:
# 지하층수 중복 요소 수 확인
df['지하층수'].value_counts()

지하층수
 0.0     15575
 1.0     11053
 2.0      6136
 3.0      2755
 4.0      1187
 5.0       557
 6.0       203
 7.0       169
 8.0        88
 9.0        13
 15.0        3
 16.0        3
 13.0        2
 10.0        2
 20.0        2
 18.0        2
 14.0        1
 21.0        1
-1.0         1
 19.0        1
 23.0        1
 12.0        1
Name: count, dtype: int64

In [6]:
# 지하층수가 0인 데이터 제외
df = df[df['지하층수'] != 0.0]
df['지하층수'].value_counts()

지하층수
 1.0     11053
 2.0      6136
 3.0      2755
 4.0      1187
 5.0       557
 6.0       203
 7.0       169
 8.0        88
 9.0        13
 15.0        3
 16.0        3
 13.0        2
 10.0        2
 20.0        2
 18.0        2
 14.0        1
 21.0        1
-1.0         1
 19.0        1
 23.0        1
 12.0        1
Name: count, dtype: int64

In [7]:
# 지하층수가 -1.0인 데이터 제외
df = df[df['지하층수'] != -1.0]
df['지하층수'].value_counts()

지하층수
1.0     11053
2.0      6136
3.0      2755
4.0      1187
5.0       557
6.0       203
7.0       169
8.0        88
9.0        13
15.0        3
16.0        3
10.0        2
20.0        2
13.0        2
18.0        2
14.0        1
21.0        1
19.0        1
23.0        1
12.0        1
Name: count, dtype: int64

In [8]:
df.shape

(42796, 42)

In [9]:
df['주용도코드명'].unique()

array(['공동주택', '판매시설', '제1종근린생활시설', '교습소', '상점(소매점)', '기타제1종근린생활시설',
       '복리시설', '아파트', '학원', '근린생활시설', '판매및영업시설', '사무소', '제2종근린생활시설',
       '노유자시설', '업무시설', '교육연구및복지시설', '노인복지시설', '문화및집회시설', '의원', '교육연구시설',
       '운수시설', '소매점', nan, '체력단련장', '위험물저장및처리시설', '부대시설', '운동시설', '숙박시설',
       '단독주택', '의료시설', '멀티미디어문화컨텐츠설비제공업소', '부동산중개업소', '일반음식점', '세탁소',
       '자동차관련시설', '제조업소', '독서실', '기타제2종근린생활시설', '미용원', '종교시설', '기타사무소',
       '이(미)용원', '기타창고시설', '금융업소', '한의원', '수련시설', '동물미용실', '자원순환관련시설',
       '골프연습장', '영유아보육시설', '예식장', '안마원', '휴게음식점', '체육도장', '생활편익시설',
       '위락시설', '유치원', '교회', '기타교육연구시설', '기타판매시설', '부동산중개사무소', '기타노유자시설',
       '이용원', '기타연구소', '게임제공업소', '마을공동작업소', '공공용시설', '창고시설', '어린이집', '공장',
       '당구장', '방송통신시설', '사진관', '가설건축물', '제과점', '동물병원', '발전시설', '목욕장',
       '놀이형시설', '치과의원', '직업훈련소', '교육(연수)원', '청소년게임제공업소'], dtype=object)

In [10]:
# 주거용 건물 항목들을 리스트로 묶기
types = ['공동주택', '아파트', '단독주택']

# 필터링
df = df[df['주용도코드명'].isin(types)]
df['주용도코드명'].value_counts()

주용도코드명
공동주택    35497
단독주택      256
아파트        21
Name: count, dtype: int64

In [11]:
for i in range(42):
  print(df.iloc[:,i].value_counts())

대지위치
서울특별시 송파구 가락동 162       304
서울특별시 은평구 증산동 205-33    234
서울특별시 노원구 중계동 30-3      196
서울특별시 송파구 신천동 7         171
서울특별시 관악구 봉천동 1712      158
                       ...
서울특별시 서초구 양재동 16-8        1
서울특별시 강남구 논현동 106         1
서울특별시 중구 장충동2가 211        1
서울특별시 강북구 수유동 567-19      1
서울특별시 강북구 수유동 739         1
Name: count, Length: 4648, dtype: int64
시군구코드명
서울특별시 송파구      3023
서울특별시 서초구      2320
서울특별시 은평구      2252
서울특별시 강서구      2137
서울특별시 강동구      2056
서울특별시 강남구      2017
서울특별시 구로구      1950
서울특별시 노원구      1896
서울특별시 동작구      1617
서울특별시 성북구      1521
서울특별시 영등포구     1386
서울특별시 서대문구     1369
서울특별시 동대문구     1364
서울특별시 마포구      1258
서울특별시 중랑구      1219
서울특별시 관악구      1199
서울특별시 성동구      1121
서울특별시 용산구      1071
서울특별시 양천구      1011
서울특별시 도봉구       792
서울특별시 강북구       787
서울특별시 금천구       652
서울특별시 중구        520
서울특별시 광진구       378
서울특별시 종로구       259
Name: count, dtype: int64
법정동코드명
진관동       1167
마곡동        838
봉천동        704
방배동        682
가락동        676
          ...
원남동          1
충정로2가        1
영천동          1
안암동4가        1
영등포동4가       1
Name: count, Length: 289, dtype: int64
대지구분코드명
대지    29539
블록     3774
산       734
Name: count, dtype: int64
주지번
0.0       4079
1.0        369
162.0      355
30.0       338
144.0      305
          ...
1823.0       1
1754.0       1
1450.0       1
981.0        1
1522.0       1
Name: count, Length: 1334, dtype: int64
부지번
0.0       19050
1.0        2486
3.0        1087
2.0        1018
4.0         629
          ...
158.0         1
1637.0        1
383.0         1
3926.0        1
137.0         1
Name: count, Length: 252, dtype: int64
동별개요일련번호
1023100015831             1
1007401                   1
1007400                   1
1007398                   1
1007396                   1
                         ..
1000000000000000241112    1
1013100008667             1
1000000000000000222030    1
1000000000000000203503    1
1000000000000000203506    1
Name: count, Length: 35774, dtype: int64
주택대장일련번호
10010                     452
10032                     114
1023100036102             111
1024100048705             108
1014100004329             104
                         ...
1000000000000000322856      1
1000000000000000323562      1
1000000000000000286178      1
1000000000000000322443      1
1000000000000000320526      1
Name: count, Length: 7463, dtype: int64
건물명
SH아파트                             311
LH아파트                             280
관악드림타운                            244
송파창의혁신 공공주택 건설공사(2단지)             225
송파창의혁신 공공주택 건설공사(1단지)             193
                                 ...
흑석한강센트레빌2차                          1
상상로프트                               1
LC 17                               1
충정로3가 187-1 외1필지 LH매입임대주택(청년형)      1
마포구 신정동 LH매입임대주택 신축공사               1
Name: count, Length: 3769, dtype: int64
특수지명
마곡도시개발사업지구         463
은평뉴타운3지구           164
일대                 157
세곡2보금자리주택지구        147
공공주택지구             140
                  ...
410-28(833.20㎡)      1
서울특별시 강동구 천호1동       1
강동구 길동               1
주공아파트                1
서울고덕강일 공공주택지구        1
Name: count, Length: 275, dtype: int64
블록번호
2단지       146
174 일원    140
1블록       105
1단지        96
6블록        90
         ...
402         1
702         1
1359        1
169         1
12블럭        1
Name: count, Length: 190, dtype: int64
로트번호
1       88
0       54
3.0     24
6       18
블럭      17
        ..
9.0      1
68.0     1
2.0      1
96.0     1
24.0     1
Name: count, Length: 65, dtype: int64
주부속구분코드명
부속건축물    19027
주건축물     16742
Name: count, dtype: int64
동명
101동         1418
지하주차장        1183
102동          925
상가동           817
103동          678
             ...
맘스 스테이션-1       1
공유오피스           1
티하우스-2          1
맘스 스테이션-5       1
티하우스-1          1
Name: count, Length: 7838, dtype: int64
주용도코드명
공동주택    35497
단독주택      256
아파트        21
Name: count, dtype: int64
국민임대세대수
0      34558
60        43
58        34
56        28
30        25
       ...
98         1
292        1
393        1
164        1
154        1
Name: count, Length: 177, dtype: int64
공공임대5년세대수
0      35737
98         4
86         4
27         3
104        3
14         2
25         2
40         2
65         2
4          2
7          1
10         1
5          1
50         1
35         1
33         1
55         1
66         1
24         1
103        1
101        1
178        1
130        1
Name: count, dtype: int64
공공임대10년세대수
0      35356
58        13
8         13
60        12
96        11
       ...
126        1
115        1
140        1
245        1
14         1
Name: count, Length: 115, dtype: int64
공공임대기타세대수
0      34127
4         58
30        49
1         46
20        46
       ...
119        1
170        1
242        1
325        1
106        1
Name: count, Length: 216, dtype: int64
공공임대총세대수
0      33197
8         63
4         62
28        58
30        57
       ...
178        1
155        1
242        1
325        1
123        1
Name: count, Length: 250, dtype: int64
공공분양세대수
0      34048
58        65
28        50
60        48
20        45
       ...
114        1
99         1
104        1
111        1
145        1
Name: count, Length: 144, dtype: int64
사원임대세대수
0    35774
Name: count, dtype: int64
근로복지세대수
0    35774
Name: count, dtype: int64
민간임대세대수
0      32440
80        81
88        79
72        78
60        75
       ...
302        1
248        1
233        1
293        1
207        1
Name: count, Length: 293, dtype: int64
민간분양세대수
0      30424
10       356
48       105
60       103
15       100
       ...
187        1
195        1
216        1
279        1
228        1
Name: count, Length: 268, dtype: int64
구조코드명
철근콘크리트구조        33301
벽돌구조              736
철골철근콘크리트구조        476
라멘조               417
기타조적구조            237
철골콘크리트구조          135
일반철골구조            105
경량철골구조             88
강파이프구조             55
블록구조               39
기타구조               32
철골철근콘크리트합성구조       30
프리케스트콘크리트구조        21
일반목구조              13
기타콘크리트구조           12
기타강구조              12
조적구조                4
석구조                 2
조립식판넬조              2
컨테이너조               1
기타철골철근콘크리트구조        1
Name: count, dtype: int64
지붕코드명
(철근)콘크리트    31123
기타지붕         3446
기와            127
슬레이트           67
Name: count, dtype: int64
건축면적
0.0000       17100
16.4800         47
8.8800          40
12.9600         39
12.0000         36
             ...
526.4200         1
693.9000         1
1106.7700        1
609.7022         1
441.2896         1
Name: count, Length: 12043, dtype: int64
연면적
0.000        3770
8.880          53
12.000         50
8.640          48
16.480         45
             ...
48013.760       1
61.980          1
815.560         1
9119.630        1
646.149         1
Name: count, Length: 24486, dtype: int64
지하면적
0.0000        17965
582.9200         21
403.6800         18
755.9500         18
76324.2200       16
              ...
12246.8000        1
119.7460          1
98.8323           1
2710.4500         1
43472.0627        1
Name: count, Length: 13981, dtype: int64
용적률산정연면적
0.0000        16723
8.8800           49
16.4800          46
12.0000          39
12.9600          38
              ...
20.5400           1
1484.3100         1
7796.9300         1
15414.6800        1
694.2284          1
Name: count, Length: 13638, dtype: int64
지하층수
1.0     10171
2.0      5598
3.0      2493
4.0      1023
5.0       440
6.0       139
7.0       130
8.0        48
9.0        13
15.0        3
16.0        3
10.0        2
20.0        2
13.0        2
18.0        2
14.0        1
21.0        1
19.0        1
23.0        1
12.0        1
Name: count, dtype: int64
지상층수
1.0     6317
0.0     5872
15.0    1953
2.0     1073
12.0     790
18.0     743
20.0     738
6.0      711
10.0     572
14.0     568
13.0     563
16.0     550
19.0     545
7.0      494
5.0      461
25.0     454
17.0     452
22.0     431
3.0      421
11.0     413
21.0     320
9.0      318
4.0      301
23.0     300
24.0     296
8.0      291
29.0     192
27.0     166
35.0     149
28.0     125
26.0     119
33.0      53
32.0      47
36.0      45
34.0      43
30.0      37
31.0      27
40.0      17
43.0      15
45.0      15
39.0      14
46.0      12
37.0      11
44.0      10
41.0      10
47.0      10
49.0       9
38.0       9
56.0       4
48.0       3
55.0       3
42.0       3
65.0       2
50.0       2
59.0       2
51.0       1
57.0       1
53.0       1
Name: count, dtype: int64
높이
0.00      15763
3.60        305
3.50        253
3.80        183
5.00        179
          ...
95.95         1
17.47         1
117.90        1
62.14         1
117.98        1
Name: count, Length: 2761, dtype: int64
승용승강기인용수정보
0.0      4363
1.0      4126
2.0      2896
3.0      1231
4.0       518
5.0       165
6.0       135
7.0       107
8.0        53
10.0       23
9.0        18
11.0       15
12.0       12
17.0        9
13.0        6
15.0        5
16.0        4
27.0        4
18.0        4
14.0        3
20.0        3
19.0        2
28.0        2
34.0        2
23.0        2
24.0        2
36.0        2
21.0        2
22.0        2
65.0        1
415.0       1
Name: count, dtype: int64
비상용승강기인용수정보
0.0     5460
2.0     3571
1.0     2215
3.0     1217
4.0      547
5.0      199
6.0      128
7.0       62
9.0       34
25.0      33
8.0       27
10.0      21
14.0      13
13.0      10
12.0       8
11.0       5
29.0       5
15.0       5
19.0       4
16.0       3
21.0       2
26.0       2
20.0       2
18.0       2
22.0       2
17.0       2
77.0       1
72.0       1
28.0       1
31.0       1
33.0       1
23.0       1
75.0       1
Name: count, dtype: int64
층시작높이값
2.80     3399
2.90     2166
2.60     2058
3.00     1115
2.70     1086
         ...
9.56        1
13.95       1
5.66        1
4.62        1
7.24        1
Name: count, Length: 381, dtype: int64
반자높이값
2.3     6568
2.4     3322
2.3     2275
2.4     1191
0.0     1166
        ...
4.32       1
6.35       1
5.35       1
0.6        1
1.5        1
Name: count, Length: 295, dtype: int64
계단유효너비
0.000     21385
1.200     11387
1.250       480
1.300       363
2.600       302
          ...
3.400         1
12.250        1
1.202         1
1.650         1
1.680         1
Name: count, Length: 146, dtype: int64
복도너비
0.000    28414
1.500     2845
1.800      852
1.600      592
1.200      583
         ...
3.680        1
4.940        1
3.750        1
1.965        1
2.190        1
Name: count, Length: 181, dtype: int64
외벽두께
0.0         14370
20.0         8132
18.0         2433
30.0         2389
25.0         1654
            ...
150180.0        1
180150.0        1
25.3            1
29.1            1
32.1            1
Name: count, Length: 177, dtype: int64
인접세대벽두께
0.0      23432
20.0      4915
18.0      3565
25.0       932
180.0      460
         ...
29.0         1
13.0         1
12.5         1
28.5         1
29.1         1
Name: count, Length: 69, dtype: int64

In [12]:
# 필요없는 칼럼 제외
# Index(['대지위치', '시군구코드명', '법정동코드명', '대지구분코드명', '주지번', '부지번', '동별개요일련번호',
# '주택대장일련번호', '건물명', '특수지명', '블록번호', '로트번호', '주부속구분코드명', '동명', '주용도코드명',
# '국민임대세대수', '공공임대5년세대수', '공공임대10년세대수', '공공임대기타세대수', '공공임대총세대수',
# '공공분양세대수', '사원임대세대수', '근로복지세대수', '민간임대세대수', '민간분양세대수', '구조코드명', '지붕코드명',
# '건축면적', '연면적', '지하면적', '용적률산정연면적', '지하층수', '지상층수', '높이', '승용승강기인용수정보',
# '비상용승강기인용수정보', '층시작높이값', '반자높이값', '계단유효너비', '복도너비', '외벽두께', '인접세대벽두께'],

# 필요 칼럼 : 시군구코드명, 법정동코드명, 지하층수, 지하면적

In [13]:
df = df[['시군구코드명', '법정동코드명', '주지번', '부지번', '지하층수', '지하면적']]

In [14]:
df.head()

       시군구코드명 법정동코드명  주지번  부지번  지하층수       지하면적
3  서울특별시 성북구    하월곡동  0.0  0.0   2.0  12014.967
4  서울특별시 성북구    하월곡동  0.0  0.0   2.0    150.530
5  서울특별시 성북구    하월곡동  0.0  0.0   2.0    264.210
7  서울특별시 성북구    하월곡동  0.0  0.0   1.0    144.240
8  서울특별시 성북구    하월곡동  0.0  0.0   1.0     59.240

In [15]:
df = df.reset_index()

In [16]:
df = df.drop(['index'], axis = 1)
df.head()

       시군구코드명 법정동코드명  주지번  부지번  지하층수       지하면적
0  서울특별시 성북구    하월곡동  0.0  0.0   2.0  12014.967
1  서울특별시 성북구    하월곡동  0.0  0.0   2.0    150.530
2  서울특별시 성북구    하월곡동  0.0  0.0   2.0    264.210
3  서울특별시 성북구    하월곡동  0.0  0.0   1.0    144.240
4  서울특별시 성북구    하월곡동  0.0  0.0   1.0     59.240

In [17]:
code = pd.read_excel('C:/Users/hyeon/OneDrive/Desktop/2026-1/공모전/데이터분석/데이터/행정구역/법정동코드 조회자료.xlsx',
                     dtype = {'법정동코드' : str})

c:\Users\hyeon\anaconda3\envs\cv_final\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [18]:
code.head()

        법정동코드           법정동명
0  1100000000          서울특별시
1  1111000000      서울특별시 종로구
2  1111010100  서울특별시 종로구 청운동
3  1111010200  서울특별시 종로구 신교동
4  1111010300  서울특별시 종로구 궁정동

In [19]:
# 1. 반지하 데이터(df) 텍스트 합치기
df['시군구코드명'] = df['시군구코드명'].str.strip()
df['법정동코드명'] = df['법정동코드명'].str.strip()
df['법정동명'] = df['시군구코드명'] + " " + df['법정동코드명']

# 2. 법정동코드 데이터 공백 제거
code['법정동명'] = code['법정동명'].str.strip()

# 3. 데이터 병합 
final_df = pd.merge(df, code[['법정동명', '법정동코드']], on='법정동명', how='left')
final_df[['법정동명', '법정동코드', '지하층수', '지하면적']].head()

             법정동명       법정동코드  지하층수       지하면적
0  서울특별시 성북구 하월곡동  1129013600   2.0  12014.967
1  서울특별시 성북구 하월곡동  1129013600   2.0    150.530
2  서울특별시 성북구 하월곡동  1129013600   2.0    264.210
3  서울특별시 성북구 하월곡동  1129013600   1.0    144.240
4  서울특별시 성북구 하월곡동  1129013600   1.0     59.240

In [20]:
basement_counts = final_df.groupby('법정동코드').size().reset_index(name = '반지하_개수')
basement_counts

          법정동코드  반지하_개수
0    1111010100      13
1    1111011500      19
2    1111015900       1
3    1111016700       1
4    1111017000       3
..          ...     ...
286  1174010600     157
287  1174010700     140
288  1174010800     187
289  1174010900     252
290  1174011000     672

[291 rows x 2 columns]

In [21]:
# 지도 데이터 불러오기
gdf = gpd.read_file("C:/Users/hyeon/OneDrive/Desktop/2026-1/공모전/데이터분석/데이터/행정구역/행정구역_법정동_경계/admstr_zone_lgldong_bndry_24.shp", encoding='cp949')
gdf.head()

,EMD_CD,COL_ADM_SE,EMD_NM,SGG_OID,geometry
0,11110101,11110,청운동,1036,"POLYGON ((196593.774 554114.361, 196611.342 55..."
1,11110102,11110,신교동,307,"POLYGON ((196912.513 554003.597, 196920.988 55..."
2,11110103,11110,궁정동,1034,"POLYGON ((197377.934 553847.046, 197388.359 55..."
3,11110104,11110,효자동,309,"POLYGON ((197664.978 553742.317, 197663.825 55..."
4,11110105,11110,창성동,316,"POLYGON ((197662.098 553585.836, 197662.501 55..."

In [ ]:
# 앞 8자리만 잘라내어 'merge_key'를 만듦

gdf['merge_key'] = gdf['EMD_CD'].astype(str).str[:8]
basement_counts['merge_key'] = basement_counts['법정동코드'].astype(str).str[:8]

In [ ]:
# 8자리 'merge_key'를 기준으로 병
merged_gdf = gdf.merge(basement_counts, on='merge_key', how='left')

# 반지하 주택이 하나도 없는 법정동은 NaN이 되므로 0으로 채움
merged_gdf['반지하_개수'] = merged_gdf['반지하_개수'].fillna(0)

In [24]:
m = merged_gdf.explore(
    column='반지하_개수',        
    cmap='YlOrRd',                       # 노란색에서 빨간색으로 갈수록 개수가 많음을 의미
    tooltip=['EMD_NM', '반지하_개수'],    # 마우스를 올리면 '동이름'과 '개수'가 뜸
    style_kwds={'weight': 0.5, 'color': 'gray', 'fillOpacity': 0.8}
)

m.save("seoul_basement_map.html")